- name: Install Docker-Registry using Helm
  hosts: labsys-k1
  remote_user: sysadmin
  become: false
 
  tasks:

  # Helm Repo

  - name: Copy values.
    ansible.builtin.copy:
      src: "registry/helm/values.yaml"
      dest: "/tmp/registry_values.yaml"

  - name: Add docker-registry repo
    kubernetes.core.helm_repository:
      name: twuni
      repo_url: https://helm.twun.io

  - name: Deploy latest version of docker-registry chart inside default namespace
    kubernetes.core.helm:
      name: registry
      chart_ref: twuni/docker-registry
      release_namespace: default
      wait: true
      values_files:
        - /tmp/registry_values.yaml