- name: Create a chart and add it local helm repo
  hosts: labsys-k1
  remote_user: sysadmin
 
  vars:
    app_name: ""

  tasks:
  - name: Create mychart chart and add to index
    block:
    - name: Create new chart named mychart
      shell: helm create mychart
      register: helm_create

    - name: Create charts directory.
      ansible.builtin.file:
        path: charts
        state: directory
        mode: '0755'

    - name: Package chart
      shell: helm package mychart/ -d charts/

    - name: Create index of packages
      shell: helm repo index charts/

    - name: Show index
      shell: cat charts/index.yaml
      register: index_content
    - debug: msg="{{ index_content.stdout }}"

  - name: Update chart version and add to index
    block:
    - name: Update chart version
      shell: 'sed -i ''s/^version:.*$/version: 0.2.0/'' mychart/Chart.yaml'

    - name: Package chart
      shell: helm package mychart/ -d charts/

    - name: Create index of packages
      shell: helm repo index charts/

    - name: Show index
      shell: cat charts/index.yaml
      register: index_content
    - debug: msg="{{ index_content.stdout }}"

  - name: Create otherchart chart and add to index
    block:
    - name: Create new chart named otherchart
      shell: helm create otherchart
      register: helm_create

    - name: Create charts directory.
      ansible.builtin.file:
        path: charts2
        state: directory
        mode: '0755'

    - name: Package chart
      shell: helm package otherchart/ -d charts2/

    - name: Create index of packages
      shell: helm repo index --merge charts/index.yaml charts2/

    - name: Copy packages so index is valid.
      shell: cp charts/*.tgz charts2/

    - name: Show index
      shell: cat charts2/index.yaml
      register: index_content
    - debug: msg="{{ index_content.stdout }}"

  - name: Start nginx instance to host charts.
    block:

    # Helm Repo

    - name: Ensure bitnami repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    # Volumes

    - name: Create helm directory.
      become: true
      ansible.builtin.file:
        path: /data/helm
        state: directory
        mode: '0775'

    - name: Copy packages to helm directory.
      become: true
      shell: cp /home/sysadmin/charts2/* /data/helm

    - name: Init volumes.
      ansible.builtin.copy:
        src: "helm_repo/storage.yaml"
        dest: "/tmp/storage.yaml"

    - shell: "kubectl apply -f /tmp/storage.yaml"

    # Helm Release

    - name: Copy values.
      ansible.builtin.copy:
        src: "helm_repo/helm/values.yaml"
        dest: "/tmp/helm_nginx_values.yaml"

    - name: Deploy latest version of docker-registry chart inside default namespace
      kubernetes.core.helm:
        name: helm-repo
        chart_ref: bitnami/nginx
        release_namespace: default
        wait: true
        values_files:
          - /tmp/helm_nginx_values.yaml

  - name: Run app from hosted charts repo
    block:

    # Helm Repo

    - name: Add helm local repo from helm-repo-nginx repo
      kubernetes.core.helm_repository:
        name: helm-local
        repo_url: http://localhost:32001

    - name: Deploy release using helm-repo-nginx repo
      kubernetes.core.helm:
        name: helm-local-demo
        chart_ref: helm-local/mychart
        release_namespace: default
        wait: true

    - name: Deploy release using helm-repo-nginx repo with version 0.1.0
      kubernetes.core.helm:
        name: helm-local-demo
        chart_ref: helm-local/mychart
        chart_version: 0.1.0
        release_namespace: default
        wait: true

  - name: Update chart version and add to index
    block:
    - name: Update chart version
      shell: 'sed -i ''s/^version:.*$/version: 0.3.0/'' mychart/Chart.yaml'

    - name: Package chart
      shell: helm package mychart/ -d charts2/

    - name: Create index of packages
      shell: helm repo index charts2/

    - name: Show index
      shell: cat charts2/index.yaml
      register: index_content
    - debug: msg="{{ index_content.stdout }}"

    - name: Copy packages to helm directory.
      become: true
      shell: cp -f /home/sysadmin/charts2/* /data/helm

    - name: Deploy release using helm-repo-nginx repo with version 0.3.0
      kubernetes.core.helm:
        update_repo_cache: true
        name: helm-local-demo
        chart_ref: helm-local/mychart
        chart_version: 0.3.0
        release_namespace: default
        wait: true