- name: Install Helm
  hosts: labsys-k1
  remote_user: sysadmin
  become: yes
  
  vars:
    version: "helm-v3.10.3-linux-amd64"    
    helm_checksum: "cc5223b23fd2ccdf4c80eda0acac7a6a5c8cdb81c5b538240e85fe97aa5bc3fb"

  tasks:

  - name: Download Helm binary
    get_url:
      url: "https://get.helm.sh/{{version}}.tar.gz"
      dest: /tmp/helm.tar.gz

  - name: Download Helm binary
    get_url:
      url: "https://get.helm.sh/{{version}}.tar.gz.sha256sum"
      dest: /tmp/helm.tar.gz.sum

  - name: Calculate Tar Checksum
    shell: sha256sum /tmp/helm.tar.gz | cut -d ' ' -f 1
    register: helm_tar_checksum_calculated

  - name: Register Tar Checksum Downloaded
    shell: cat /tmp/helm.tar.gz.sum | cut -d ' ' -f 1
    register: helm_tar_checksum_downloaded

  - name: Compare Helm checksum
    assert:
      that:
        - helm_tar_checksum_downloaded.stdout == helm_tar_checksum_calculated.stdout

  - name: Extract Helm binary
    ansible.builtin.unarchive:
      src: /tmp/helm.tar.gz
      dest: /usr/local/bin
      include:
      - linux-amd64/helm
      extra_opts:
      - --strip-components=1
      remote_src: yes
      creates: /usr/local/bin/helm

  - name: Calculate Binary Checksum
    shell: sha256sum /usr/local/bin/helm | cut -d ' ' -f 1
    register: helm_checksum_calculated

  - name: Compare Helm checksum
    assert:
      that:
        - helm_checksum_calculated.stdout == "{{ helm_checksum }}"