- name: Install Wordpress using Helm
  hosts: labsys-k1
  remote_user: sysadmin
  become: false
 
  tasks:

  # Volumes

  - name: Init volumes.
    ansible.builtin.copy:
      src: "wordpress/storage.yaml"
      dest: "/tmp/storage.yaml"

  - shell: "kubectl apply -f /tmp/storage.yaml"

  # Helm Repo

  - name: Copy values.
    ansible.builtin.copy:
      src: "wordpress/helm/values.yaml"
      dest: "/tmp/wordpress_values.yaml"

  - name: Add wordpress repo
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: https://charts.bitnami.com/bitnami

  - name: Deploy latest version of wordpress chart inside wordpress namespace
    kubernetes.core.helm:
      name: wordpress
      chart_ref: bitnami/wordpress
      release_namespace: default
      wait: true
      values_files:
        - /tmp/wordpress_values.yaml