- name: Initialize Single Node K8S Clusters
  hosts: labsys-k1
  remote_user: sysadmin
  become: yes

  tasks: 

    - name: Configure Kubernetes Dependencies
      block:
        - name: Install Containerd
          ansible.builtin.import_role:
            name: labrats_work.modules_ansible.containerd
        - name: Install OpenISCI
          ansible.builtin.import_role:
            name: labrats_work.modules_ansible.open_isci

    - name: Install Kubernetes Node Compenents
      ansible.builtin.import_role:
        name: labrats_work.modules_ansible.kubernetes_node

    - name: Configure Node as Master
      ansible.builtin.import_role:
        name: labrats_work.modules_ansible.kubernetes_master
      vars:
        kubernetes_iface: "{{ kubernetes_iface_name }}"

    - name: Remove taints, this is a single node test cluster.
      become: no
      shell: kubectl taint nodes --all {{item}}
      ignore_errors: true
      with_items:
      - node-role.kubernetes.io/control-plane-
      - node-role.kubernetes.io/master-