apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: helm-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: helm-data
spec:
  storageClassName: helm-local
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/data/helm"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helm-data
spec:
  storageClassName: helm-local
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi