apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-local
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-app
spec:
  storageClassName: wordpress-local
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data/wordpress/app"
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mariadb
spec:
  storageClassName: wordpress-local
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: "/data/wordpress/mariadb"
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-app-data
spec:
  storageClassName: wordpress-local
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi