apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-local
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1
spec:
  storageClassName: wordpress-local
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data/vol1"
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol2
spec:
  storageClassName: wordpress-local
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data/vol2"
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol3
spec:
  storageClassName: wordpress-local
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/data/vol3"
  volumeMode: Filesystem